# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14499ca9e86f20387fcc831f934fb9bbe0c2a5315795e2bdb546213ef191288bb76f2dd3b52fbb6ff2e1923619ae70175e2e2b90aa086aca41265c322e6253fb

test:
  secret_key_base: 1d616cd9cf3fbbf9e5568ff6c4510b3d2d25c5fba5f0228c9666c475c80418b2aecc516ffc5d3510629b9017f2bc0c7745ef32cb4623d5cb52f846e855b901e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
